# Generated by Django 5.2.3 on 2025-06-23 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title or short description of the todo item.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='An optional longer description for the todo item.', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Indicates whether the todo item has been completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the todo item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the todo item was last updated.')),
                ('owner', models.ForeignKey(help_text='The user who owns this todo item.', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo Item',
                'verbose_name_plural': 'Todo Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
