# Generated by Django 5.2.3 on 2026-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Optional category label (e.g., Work, Personal).', max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.CharField(blank=True, default='', help_text='Optional due date as YYYY-MM-DD string (frontend uses this format).', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, default='', help_text='Optional priority (easy/medium/hard/urgent). Stored as a string for frontend compatibility.', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of subtasks (frontend sends an array).'),
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.CharField(blank=True, default='', help_text="Optional scheduled time as a display string (e.g., '09:30 AM').", max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='trashed',
            field=models.BooleanField(default=False, help_text='Soft-delete flag used by the frontend Trash view.'),
        ),
    ]
